AllCops:
  Exclude:
    - moduleroot/spec/spec_helper.rb
    - vendor/**/*

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 120

# dealbreaker:
Style/TrailingComma:
  Enabled: false
